version: '3'

services:
    web:
        image: coffeemate/nodejs
        restart: unless-stopped
        ports:
            - "${PORT}:${PORT}"
            - "3050:3050"
        volumes:
            - .:/var/www/nsups/cpps
        working_dir: /var/www/nsups/cpps
        command: node server/index.js
        depends_on:
            - mongodb
            - redisdb

    mongodb:
        image: mongo:3.4
        restart: unless-stopped

    redisdb:
        image: redis
        restart: unless-stopped
