version: '3.3'

services:
    web:
        image: coffeemate/nodejs
        restart: unless-stopped
        ports:
            - "${PORT}:${PORT}"
            # - "3050:3050"
        volumes:
            - .:/var/www/nsups/cpps
        working_dir: /var/www/nsups/cpps
        command: npm run dev
        depends_on:
            - mongodb
            - redisdb
            - worker
        network_mode: "host"

    worker:
        image: coffeemate/nodejs
        restart: unless-stopped
        volumes:
            - .:/var/www/nsups/cpps
        working_dir: /var/www/nsups/cpps
        command: node server/node_modules/queue/worker.js
        depends_on:
            - mongodb
            - redisdb
        network_mode: "host"

    mongodb:
        image: mongo:3.4
        restart: unless-stopped
        ports:
            - "27018:27017"
        volumes:
            - type: "volume"
              source: ../data/mongodb_backup
              target: /root/volumes/cpps
              consistency: "consistent"
            
            - type: "volume"
              source: ../data/mongodb_data
              target: /data/db
              consistency: "consistent"

    redisdb:
        image: redis
        restart: unless-stopped
        ports:
            - "6378:6379"
        volumes:
            - type: "volume"
              source: ../data/redisdb_data
              target: /data
              consistency: "consistent"

