module.exports = {
    GetOjInfo: 'GetOjInfo',
    GatewayAddItems: 'GatewayAddItems',
    GatewayInit: 'GatewayInit',
    GatewayDeleteItem: 'GatewayDeleteItem',
    fetchProfile: 'fetchProfile',
    setOjUsername: 'setOjUsername',
    unsetOjUsername: 'unsetOjUsername',
    syncSolveCount: 'syncSolveCount',
    fetchClassrooms: 'Coach/fetchClassrooms',
    createNewClassroom: 'createNewClassroom',
    fetchClassroom: 'fetchClassroom',
    fetchContests: 'fetchContests',
    addNewStudentToClassroom: 'addNewStudentToClassroom',
    removeStudentFromClasssroom: 'removeStudentFromClasssroom',
    fetchProblemLists: 'fetchProblemLists',
    createNewProblemList: 'createNewProblemList',
    fetchProblemList: 'fetchProblemList',
    addProblemToProblemList: 'addProblemToProblemList',
    removeProblemFromProblemList: 'removeProblemFromProblemList',
    addProblemListToClassroom: 'addProblemListToClassroom',
    removeProblemListFromClassroom: 'removeProblemListFromClassroom',
    addNewContestToClassroom: 'addNewContestToClassroom',
    addNewStandingsToContest: 'addNewStandingsToContest',
    updateRatingsByContest: 'updateRatingsByContest',
}
