module.exports = {
    GetOjInfo: 'GetOjInfo',
    GatewayAddItems: 'GatewayAddItems',
    GatewayInit: 'GatewayInit',
    GatewayDeleteItem: 'GatewayDeleteItem',
    fetchProfile: 'fetchProfile',
    setOjUsername: 'setOjUsername',
    unsetOjUsername: 'unsetOjUsername',
    fetchClassrooms: 'fetchClassrooms',
    createNewClassroom: 'createNewClassroom',
    fetchClassroom: 'fetchClassroom',
    addNewStudentToClassroom: 'addNewStudentToClassroom',
    fetchProblemLists: 'fetchProblemLists',
    createNewProblemList: 'createNewProblemList',
    fetchProblemList: 'fetchProblemList',
    createNewProblem: 'createNewProblem',
}
