const getters = {
    sidebar: state => state.app.sidebar,
    device: state => state.app.device,
    token: state => state.user.token,
    username: state => state.user.username,
    roles: state => state.user.roles,
    email: state => state.user.email,
    ojInfo: state => state.ojInfo.ojInfo,
    gatewayItems: state => state.gateway.itemList,
    gatewayRoot: state => state.gateway.root,
    gatewayBreadcrumb: state => state.gateway.gatewayBreadcrumb,
    user: state => state.user,
    profile: state => state.profile,
    coach_classrooms: state => state.classrooms.Coach.classrooms,
    student_classrooms: state => state.classrooms.Student.classrooms,
    classroom: state => state.classroom.classroom,
    contests: state => state.classroom.contests,
    problemLists: state => state.problemLists.problemLists,
    problemList: state => state.problemList.problemList,
}
export default getters
